// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6ydzC5xSlqeZZOE_FFbr8b_HMXvq5KCU',
    appId: '1:891877765830:web:03175d5e4f4a3eccf75dc7',
    messagingSenderId: '891877765830',
    projectId: 'doc-in-the-box',
    authDomain: 'doc-in-the-box.firebaseapp.com',
    storageBucket: 'doc-in-the-box.appspot.com',
    measurementId: 'G-6ENPZWSW49',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxfLzi2FvdOHRjWlmmIUkNayYNs7d9dTU',
    appId: '1:891877765830:android:4a306f54a7df5e44f75dc7',
    messagingSenderId: '891877765830',
    projectId: 'doc-in-the-box',
    storageBucket: 'doc-in-the-box.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWR0o7_Cu7ZinUYuO5b69HqGIyqBGXxQ8',
    appId: '1:891877765830:ios:fe21ecf0311701a3f75dc7',
    messagingSenderId: '891877765830',
    projectId: 'doc-in-the-box',
    storageBucket: 'doc-in-the-box.appspot.com',
    iosClientId: '891877765830-qompec5ht2qji2mcrdcckk636eusidmr.apps.googleusercontent.com',
    iosBundleId: 'com.example.practiceapp.practiceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWR0o7_Cu7ZinUYuO5b69HqGIyqBGXxQ8',
    appId: '1:891877765830:ios:fe21ecf0311701a3f75dc7',
    messagingSenderId: '891877765830',
    projectId: 'doc-in-the-box',
    storageBucket: 'doc-in-the-box.appspot.com',
    iosClientId: '891877765830-qompec5ht2qji2mcrdcckk636eusidmr.apps.googleusercontent.com',
    iosBundleId: 'com.example.practiceapp.practiceApp',
  );
}
